### ISSUE TITLE
[question] Hacs

### ISSUE THREAD

**Issue by rdehuyss** [daenny/climate_group#1]
Small question: is there at reason why this is not a native HACS component? Adding a component to HACS takes 5 minutes.

Thanks for the great work!

**Comment by rdehuyss** [comment]
P.s.: to clarify, just add your repo to this file: https://github.com/custom-components/hacs/blob/data/repositories/integration

**Comment by daenny** [comment]
For some reasons I did not get notifications for the issues. Will do so!

**Comment by daenny** [comment]
https://github.com/custom-components/hacs/pull/562/files
