### ISSUE TITLE
climate group does not support high & low temps

### ISSUE THREAD

**Issue by christoph-luebbe** [daenny/climate_group#11]
Hi I use SPIRIT_Z Thermostats via mqtt. There I can set high and low temperatures for Heat and eco mode. (config see below)

When I use climate_group I switching between eco to heat modes works perfectly but I do not get the thermostat with two handles to set both temperatures.

  - platform: mqtt
    name: "Thermostat Fabian"
    unique_id: "thermostat_fabian"    
    qos: 0
    modes:
      - heat
      - cool
      - 'off'
    mode_state_topic: "zwave2mqtt/31/64/1/0" 
    mode_state_template: >
      {% set values = {'"Off"':'off','"Heat"':'heat', '"Heat Eco"':'cool'} %}
      {{ values[value] if value in values.keys() else 'off' }}
    mode_command_topic: "zwave2mqtt/spirit/31/64/1/0/set"
    current_temperature_topic: "zwave2mqtt/31/49/1/1"
    min_temp: 11
    max_temp: 25
    temp_step: 0.5
    temperature_high_state_topic: "zwave2mqtt/31/67/1/1"
    temperature_high_command_topic: "zwave2mqtt/31/67/1/1/set"    
    temperature_low_state_topic: "zwave2mqtt/31/67/1/11"
    temperature_low_command_topic: "zwave2mqtt/31/67/1/11/set"

**Comment by daenny** [comment]
Should be implemented with:

https://github.com/daenny/climate_group/releases/tag/0.4.0-rc1
