### ISSUE TITLE
Auto mode don‘t work with beta

### ISSUE THREAD

**Issue by Krocko** [daenny/climate_group#15]
I have 4 tado thermostates  in the group.
With 0.2.0-beta the auto Mode don‘t work anymore. If I select the auto mode, the thermostates goes in the auto mode but the group goes back to off. 
With version 0.1.2 all is working. 
Also would it be possible, if I turn on the group, that it changes to the mode auto and not to heat?

**Comment by daenny** [comment]
can you please check if beta 0.3.0 fixed your issue?

The 'turn on' behaviour is made from homeassistant, so I think that cannot be changed here.

**Comment by Krocko** [comment]
Yes, 0.3.0-beta fixed that problem. 
Thank you very much.
