### ISSUE TITLE
Feature request: improve support for preset modes

### ISSUE THREAD

**Issue by luebbe** [daenny/climate_group#17]
it looks like right now climate_group doesn't collect the preset modes from the climate entities.
It would be nice, if climate group would logial AND the supported_features of the entities and, if all have the bit for SUPPORT_PRESET_MODE set, collect the preset modes from the devices. e.g. if all devices have `preset_modes: eco, comfort`, the group card should display these modes and allow to switch between them.

![grafik](https://user-images.githubusercontent.com/3872576/78505384-740a5500-7773-11ea-91a3-7d10829ed4cd.png)

For instance I would expect it to show "supported_features: 17" as well and list the available preset modes.

**Comment by daenny** [comment]
Did you try the latest beta 0.3.0? It contains support for preset modes

**Comment by luebbe** [comment]
No, I didn't know that you're already working on in. Guess I can't install the beta from HACS?
