### ISSUE TITLE
Can’t turn climate group off

### ISSUE THREAD

**Issue by Moooof** [daenny/climate_group#2]
When I click the Off-Button on a Thermostat card (we use Fritz Thermostats), I get this error (roughly translated from german): 
Error calling Service climate/set_hvac_mode

**Comment by mouth4war** [comment]
Same error affects other services too. This component uses operation_mode instead of hvac_mode.

**Comment by mouth4war** [comment]
Fix is to replace operation_mode with hvac_mode

**Comment by Moooof** [comment]
Works perfectly, thank you!
