### ISSUE TITLE
the EXCLUDE config is working?

### ISSUE THREAD

**Issue by blademckain** [daenny/climate_group#23]
the EXCLUDE config is working?

could you tell me how the EXCLUDE entry should be configured in configure.yaml

**Comment by daenny** [comment]
See the release notes of this release:
https://github.com/daenny/climate_group/releases/tag/0.2.0-beta

just add:
```
exclude:
- SOME_PRESET_MODE
```
It only works on preset modes. The devices which are excluded will be not taken into account for showing the current temperatures.
I.e. if a device is 'away' it could make your averages off.
