### ISSUE TITLE
Deprecation Warning: ClimateDevice is deprecated, modify ClimateGroup to extend ClimateEntity

### ISSUE THREAD

**Issue by marecabo** [daenny/climate_group#25]
Not a real issue as the integration works for me, but I encountered the following deprecation warning after upgrading to 110.1. 

```
Logger: homeassistant.components.climate
Source: components/climate/__init__.py:547
Integration: Climate (documentation, issues)
First occurred: 7:30:44 PM (1 occurrences)
Last logged: 7:30:44 PM

ClimateDevice is deprecated, modify ClimateGroup to extend ClimateEntity
```

Related: https://github.com/daenny/climate_group/blob/master/custom_components/climate_group/climate.py#L96

**Comment by daenny** [comment]
Should be solved by: https://github.com/daenny/climate_group/releases/tag/0.4.1-rc2
