### ISSUE TITLE
Version key missing

### ISSUE THREAD

**Issue by AndersTao** [daenny/climate_group#39]
With the latest version of HA (2021.3.2) this integration starts getting a warning in the log's, for a  need of a version key

`No 'version' key in the manifest file for custom integration 'climate_group'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'climate_group'`

Info: https://github.com/home-assistant/core/pull/45919

**Comment by daenny** [comment]
Merged and released!
