### ISSUE TITLE
Report hvac_action accurately instead of defaulting to heat

### ISSUE THREAD

**Issue by mouth4war** [daenny/climate_group#4]
The function needs to relay the HVAC action based on group members mode instead of either off or heat.

**Comment by matteofranceschini** [comment]
I've corrected it in my pull request, it should work with any climate device.

**Comment by b4dpxl** [comment]
Still only shows heating or off for me with your update @matteofranceschini, not idle. I think because it's relying on `state`, not `hvac_action`.

**Comment by matteofranceschini** [comment]
I'll check that, what HVAC are you using? With my Daikin seems to work!

**Comment by b4dpxl** [comment]
`generic_thermostat` and my fork, `virtual_thermostat`. Since `climate 1.0`, the **state** is always `heat`, `off`, or `cool`. The **action** is used to show what it's _actually_ doing. I've forked your fork, and added support for the `away` preset mode. I've been meaning to do a PR.

**Comment by daenny** [comment]
@b4dpxl I just made a new release from @matteofranceschini changes. Please sent a PR if your changes are working!

**Comment by b4dpxl** [comment]
PR done @daenny. I've been using this with 5 thermostats for a while now. Hopefully it doesn't break anything else :D

**Comment by mouth4war** [comment]
@b4dpxl just saw your PR and it looks almost ready. Looking forward to the merge.

**Comment by sebastien-k** [comment]
@b4dpxl @matteofranceschini @daenny 

Hello gentlemen, 
Have you solved this issue?

It doesn't work on my side (as explained here: [https://github.com/daenny/climate_group/issues/12#issue-561944534](https://github.com/daenny/climate_group/issues/12#issue-561944534))
I don't know if I made something wrong or if it's a bug.

Please let me know if you can help me.
Thanks

**Comment by emics** [comment]
Hi
also for me if one HVAC is in HEATING mode and the other is in IDLE mode the Climate Group Entity remain in **OFF**

like the screenshot below

![image](https://user-images.githubusercontent.com/1004363/75755540-1d9e9680-5d2f-11ea-869e-ac991ef267ea.png)

**Comment by daenny** [comment]
I would like some minor changes for the PR as I added in the review. I am currently not at home and under lockdown in a different country. So I have no possibility to look it until I am back eventually. If someone would like to implement the changes I could review them on my phone.

**Comment by b4dpxl** [comment]
> I would like some minor changes for the PR as I added in the review. I am currently not at home and under lockdown in a different country. So I have no possibility to look it until I am back eventually. If someone would like to implement the changes I could review them on my phone.

I think I've made all the changes requested. Primarily reporting the most common preset mode, and making the option to exclude certain presets (unless everything is in that state) configurable. Heat and Cool still take priority over Off/Idle, as these should be considered "on" (as per lights in HA)

**Comment by b4dpxl** [comment]
Minor issue, with your release if everything is filtered then it returns an empty list, so no temperatures. I also noticed that the most common preset is being done before filtering, so with 2 stats it sometimes reports "away" and sometimes "idle" even with away filtered. 

I'll do another quick PR which should sort both these points.

**Comment by daenny** [comment]
I did a refactor again. I did not like the way you checked for all modes/actions, as it meant for every new HVAC action or mode we would need to add another couple of lines. 
There was already a list of `HVAC_MODES`, so I used that, but I made my own for the actions.

Can you please check if all your functionality still works?

**Comment by andersonthomas** [comment]
it works for me, thanks
