### ISSUE TITLE
set_temperature with hvac_mode does not work

### ISSUE THREAD

**Issue by mb-software** [daenny/climate_group#47]
Hello, thanks for your great work. I noticed one issue:

I have two climate entities grouped with climate_group. The problem is that this does not work properly:

> service: climate.set_temperature
> data:
>   temperature: 20
>   hvac_mode: heat
> target:
>   entity_id: climate.office_heating

If I send a hvac_mode property together with the temperature for the set_temperature service, only the mode on the underlying entities changes. The temperature doesn't.

If I call the same service for the individual entities, it works. Also if I don't specifiy the hvac_mode on the group, the temperature changes properly.

**Comment by gatonero** [comment]
Same here. Did You find a solution?

**Comment by daenny** [comment]
Should work again with latest version
