### ISSUE TITLE
Unique ID for climate_group

### ISSUE THREAD

**Issue by Kilowatt-W** [daenny/climate_group#52]
Hello,

according to the latest HA-Updates it is possible to set different things on entities and groups.

But for that it needs to have an unique id ?

Is there an option to get a unique id per group ?

Thx from austria

Kilowatt

**Comment by mxr** [comment]
Having a similar problem. My config:

```console
$ tail /root/config/configuration.yaml 


climate:
  - platform: climate_group
    name: All Thermostats
    temperature_unit: F
    entities:
    - climate.c1
    - climate.c2
    - climate.c3
```

The entity is read-only:

<img width="889" alt="all thermostats" src="https://user-images.githubusercontent.com/252209/184902744-c6c0c5ad-590f-4807-86ee-307b9b897b0b.png">


> This entity ('climate.all_thermostats') does not have a unique ID, therefore its settings cannot be managed from the UI. See the [documentation](https://www.home-assistant.io/faq/unique_id) for more detail.

**Comment by daenny** [comment]
https://github.com/home-assistant/core/pull/77737 I hope to add this integration to the main repo

**Comment by mxr** [comment]
Great thanks!

**Comment by MrEcosse** [comment]
+1 on the Unique ID feature

**Comment by mxr** [comment]
@daenny would you be willing to backport support for a unique ID before the integration is approved in the main repo?

**Comment by daenny** [comment]
Can you try with this MR?
https://github.com/daenny/climate_group/pull/57

**Comment by mxr** [comment]
Happy to try, how do I point my install to a custom tag/branch?

**Comment by mxr** [comment]
Nevermind I found these docs https://hacs.xyz/docs/faq/select_version/ - trying now

**Comment by mxr** [comment]
I installed `1.0.0-rc5` and was able to load up the entity's settings, set a custom icon, turn off all thermostats, etc. Thanks!

![image](https://user-images.githubusercontent.com/252209/202911258-825344bf-02e5-47d8-a482-95a59ff9a836.png)

**Comment by Dunkelschunkel** [comment]
@mxr I am struggling to set a unique_id for "climate_group". Should be as simple as adding "unique_id: xxxxx-xxx" to the corresponding "climate_group" in my yaml

btw. version 1.0.0-rc5 it that i am using

**Comment by mxr** [comment]
@Dunkelschunkel your best bet is to file a new issue and include a sample of your config
