### ISSUE TITLE
deprecations since 2024.1.0

### ISSUE THREAD

**Issue by cociweb** [daenny/climate_group#68]
Hello, the following messages appeared since 2024.1.0:

- `SUPPORT_TARGET_HUMIDITY was used from climate_group, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.TARGET_HUMIDITY instead, please report it to the author of the 'climate_group' custom integration`

- `SUPPORT_FAN_MODE was used from climate_group, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.FAN_MODE instead, please report it to the author of the 'climate_group' custom integration`
- `SUPPORT_PRESET_MODE was used from climate_group, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.PRESET_MODE instead, please report it to the author of the 'climate_group' custom integration`
- `SUPPORT_SWING_MODE was used from climate_group, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.SWING_MODE instead, please report it to the author of the 'climate_group' custom integration`
- `SUPPORT_AUX_HEAT was used from climate_group, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.AUX_HEAT instead, please report it to the author of the 'climate_group' custom integration`

- `TEMP_CELSIUS was used from climate_group, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead, please report it to the author of the 'climate_group' custom integration`
- `TEMP_FAHRENHEIT was used from climate_group, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.FAHRENHEIT instead, please report it to the author of the 'climate_group' custom integration`

Do anybody have any suggestion?

**Comment by thayerfox** [comment]
Try switching to this version: https://github.com/bjrnptrsn/climate_group 

Its been working well for me.

**Comment by cociweb** [comment]
It is solved by changing the repo. Thanks for your recommendation!
